FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \ 
    apt-get install -y libjpeg-dev && \ 
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r requirements.txt

COPY app.py .

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501"]